### ISSUE TITLE
Common ornament changes item color

### ISSUE THREAD

**Issue by floatingatoll** [NigelHietala/ishtar-bugs#423]
Equipping the universal ornament "Renegade Greaves" (common quality, white background in game and in Ishtat) onto the item "Crystocrene Greaves" changes the item background color in Ishtar, but not in-game. If the greaves are masterworked, this also causes Ishtar to display the masterwork overlay onto of no color at all instead of legendary purple.

The hover pop up for the ornament itself is also different in-game than in Ishtar.

(1726)

**Comment by NigelHietala** [comment]
Can you post a screenshot?

**Comment by floatingatoll** [comment]
![image](https://user-images.githubusercontent.com/92684/122654589-6e432a00-d101-11eb-9119-2dbb9cfdc02e.png)

![image](https://user-images.githubusercontent.com/92684/122654590-700ced80-d101-11eb-8962-a7dbcfd19a87.png)

**Comment by floatingatoll** [comment]
In-game:

![image](https://user-images.githubusercontent.com/92684/122654619-a21e4f80-d101-11eb-8ff1-c4a1d37851f4.png)

![image](https://user-images.githubusercontent.com/92684/122654623-a480a980-d101-11eb-814f-90904ccdca6a.png)
