### ISSUE TITLE
Mod stat arrows should be green/red

### ISSUE THREAD

**Issue by floatingatoll** [NigelHietala/ishtar-bugs#445]
They are in game if I remember correctly:

![image](https://user-images.githubusercontent.com/92684/129488565-7880a33b-a4f3-4141-9ecf-bf002135a5cc.jpeg)

**Comment by NigelHietala** [comment]
I would love to follow the game. But none of the text comes with any hints for colors. So I could do something specific such as parse for that symbol. But I don't know if that is only in english. I'm going to close this. But maybe one day might do some manual hacks for this.
