### ISSUE TITLE
Is this supposed to show the ornament title twice?

### ISSUE THREAD

**Issue by floatingatoll** [NigelHietala/ishtar-bugs#451]
When browsing ornaments in-app, I was uncertain about the title showing twice:

![image](https://user-images.githubusercontent.com/92684/129489022-524f084a-51ba-494f-b45f-4636b8326f36.jpeg)

**Comment by NigelHietala** [comment]
Yes this is intentional. It looks so weird having no text. So I added that in to make it feel a bit more like an armor view
