### ISSUE TITLE
Collections dimmed “total” number is wrong gray

### ISSUE THREAD

**Issue by floatingatoll** [NigelHietala/ishtar-bugs#467]
Should be the same gray as the overlines, lighter than now:

![image](https://user-images.githubusercontent.com/92684/129491212-96777af5-3946-4ed1-8e67-530e11da7a29.jpeg)

![image](https://user-images.githubusercontent.com/92684/129491232-879b9d01-4973-48bf-bb0f-a4298085ab6a.jpeg)

**Comment by NigelHietala** [comment]
This is intentional. On mobile it makes them look dimmed out as in not active.  On desktop Ishtar works like in-game and only the one under your mouse cursor goes light.

**Comment by floatingatoll** [comment]
Okay. Note that I can barely make out the grayed out numbers on my iPhone, even at full brightness, due to how light they are.
