### ISSUE TITLE
Weapons shouldn’t have light level in Recently Discovered

### ISSUE THREAD

**Issue by floatingatoll** [NigelHietala/ishtar-bugs#468]
Presumably armor too, but I haven't discovered any new armor recently. I could also say that it shouldn't have ammo type (energy type) icons, if exact match to in-game is desired.

![image](https://user-images.githubusercontent.com/92684/129491362-81deab94-ef69-4b80-b930-a268c5b86dae.jpeg)

![image](https://user-images.githubusercontent.com/92684/129491457-adc8c90b-b153-4c5e-a81f-7ee836adf7a1.jpeg)

**Comment by NigelHietala** [comment]
Items in Destiny don't show power level. You hold down the modifier key to see them. Ishtar works as if that is the default. Pretty sure the modifier shows both power level and burn here.

**Comment by floatingatoll** [comment]
Huh, so it does!
