### ISSUE TITLE
Kill Trackers aren't shown correctly

### ISSUE THREAD

**Issue by andyschott** [NigelHietala/ishtar-bugs#482]
For new Witch Queen weapons, they have the kill tracker perks activated automatically. Even though I have the PvE tracker selected, Ishtar is showing both the PvE and Crucible counters.

![IMG_0765](https://user-images.githubusercontent.com/3392920/155230036-93594797-ec4a-4c0c-a425-9b67b2f5ef95.PNG)

**Comment by andyschott** [comment]
Looks like Ishtar is also showing the item as masterworked, even though I haven't masterworked it (assuming you still can?).

**Comment by NigelBreslaw** [comment]
Can you raise a separate bug for incorrect showing of masterwork

**Comment by andyschott** [comment]
Done: #484

**Comment by NigelBreslaw** [comment]
Fixed
