### ISSUE TITLE
Crafted weapons should include crafted info in the Details screen

### ISSUE THREAD

**Issue by andyschott** [NigelHietala/ishtar-bugs#485]
- Weapon's current level / progress towards next level
- Crafted date

In game screenshot:
![8b6b7b47-a138-46aa-af22-dd750b147ed7](https://user-images.githubusercontent.com/3392920/155375627-64a36e00-15da-421d-9f21-1ca301e692f0.png)

Ishtar screenshot:
![IMG_0770](https://user-images.githubusercontent.com/3392920/155375676-3509edcb-8d9a-4bde-bf88-d997b6b53421.PNG)

**Comment by NigelBreslaw** [comment]
Fixed in yesterdays build. Reopen if it isn't
