### ISSUE TITLE
Weapons which can have their Pattern extracted show progress on hover

### ISSUE THREAD

**Issue by andyschott** [NigelHietala/ishtar-bugs#486]
In game:
![5780d6de-7b29-4df3-8d5c-ade93579d71f](https://user-images.githubusercontent.com/3392920/155375916-844fef65-9596-46b8-81f5-0c4777c0eda7.jpeg)

Ishtar:
<img width="303" alt="Screen Shot 2022-02-23 at 12 35 23 PM" src="https://user-images.githubusercontent.com/3392920/155375931-fe02d7d2-aac1-401e-ab6d-677e429c9fa1.png">

(I didn't think to get a screenshot of what the game shows when inspecting the weapon in this case; I'll try to do that next time I play)

**Comment by andyschott** [comment]
These are the same weapon - I just infused it and used it between the two screenshots.

**Comment by NigelBreslaw** [comment]
Fixed
